GET http://localhost:9000/getAll

###

POST http://localhost:9000/user
Content-Type: application/json

{
    "name": "test",
    "password": "password"
}

###

POST http://localhost:9000/login
Content-Type: application/json

{
    "name": "sef",
    "password" : "uihiggugigiguig"
}

###

POST http://localhost:9000/authenticate
Content-Type: application/json

{
    "username": "test",
    "password" : "password"
}