GET http://localhost:9000/quizDashboard

###
POST http://localhost:9000/createNew
Content-Type: application/json

{
    "categoryId": 2,
    "title": "mat7",
    "desc": "sadsadasd",
    "fiqPoints": 200
    
}

###
DELETE  http://localhost:9000/delete/4

###
PATCH  http://localhost:9000/update/18
Content-Type: application/json

{
    "categoryId": 3,
    "title": "peepeepoopoo",
    "desc": "sadsadasd",
    "totalPoints": 500,
    "quizQuestion": [{
        "questionTitle": "Question 1",
        "questionDesc": "",
        "options": [{
            "option": "Option xyz",
            "optionDesc": "",
            "isCorrect": true
        }]
    },{
        "questionTitle": "Question 2",
        "questionDesc": "",
        "options": [{
            "option": "Option xyz",
            "optionDesc": "",
            "isCorrect": true
        }]
    }]
    
}

###

POST http://localhost:9000/register 
Content-Type: application/json

{
    "name": "Jason Teo", 
    "password": "12345678"
}

###

POST http://localhost:9000/authenticate 
Content-Type: application/json

{
    "username": "Jason Teo", 
    "password": "12345678"
}

###

GET http://localhost:9000/category

###

POST http://localhost:9000/category
Content-Type: application/json

{
    "catName":"Intellectual Property",
    "catDesc":"IP for short."
    
}

###
DELETE  http://localhost:9000/category/4


###
PATCH http://localhost:9000/category/15
Content-Type: application/json

{
    "catName":"Intellectual Property",
    "catDesc":"IP for short."
    
}